@startuml

class FileInput {
  +readData()
}

class DataParser {
  +parseData(List<String> rawData)
}

class FileOutput {
  +writeTable(List<String> dataTable)
}

class Solution42 {
+main(String[])
}

Solution42 -- FileInput
Solution42 -- DataParser
Solution42 -- FileOutput


@enduml