@startuml

class InputClass {
  +getSiteNameFromUser()
  +getAuthorFromUser()
  +askIfJavaScriptFolder()
  +askIfCssFolder()
  -getYesOrNo
}


class OutputClass {
  +createWebFolder(String siteName)
  +buildIndexHtml(String siteName, String author)
  +createIndexHtml(String siteName, String siteName, List<String> indexHtml)
  +createJavaScriptFolder(String siteName, Boolean javaScriptFolder)
  +createCssFolder(String siteName, Boolean cssFolder)
}

@enduml