@startuml

class InputClass {
  +readFile()
}

class CalcClass {
  +countOccurrences(String data)
}


class OutputClass {
  +printHistogram(List<Map<String, Integer>> frequencies)
  -sortFrequencies(Map<String, Integer> frequencies)
  -longestWordLength(Set<String> words)
}

@enduml