@startuml

class InputClass {
  +readFile()
}

class CalcClass {
  +countOccurrences(String data)
}


class OutputClass {
  +printHistogram(List<Map<String, Integer>> frequencies)
  -sortFrequencies(Map<String, Integer> frequencies)
  -longestWordLength(Set<String> words)
}

class Solution46 {
+main(String[])
}

Solution46 -- InputClass
Solution46 -- CalcClass
Solution46 -- OutputClass

@enduml