@startuml

class FileInput {
  +readNames(String inputFile)
}

class NameSorter {
  +sortNames(List<String> names)
}

class FileOutput {
  +writeNames(List<String> names, String outputFile)
}
class Solution41 {
+main(String[])
}

Solution41 -- FileInput
Solution41 -- NameSorter
Solution41 -- FileOutput



@enduml