@startuml

class InputClass {
  +importJson(String dataFile)
  -processData()
}

class SearchClass {
  +getSearchStringFromUser()
  +searchProductList(List<Map<String, String>> productList)
}

class OutputClass {
  +print(Map<String, String> productInfo)
}

class Solution44 {
+main(String[])
}

Solution44 -- InputClass
Solution44 -- SearchClass
Solution44 -- OutputClass

@enduml