@startuml

class InputClass {
  +importJson()
  -processData()
}

class SearchClass {
  +getSearchStringFromUser()
  +searchProductList(List<Map<String, String>> productList)
}

class OutputClass {
  +print(Map<String, String> productInfo)
}

@enduml